name: Node setup and install
description: Use .nvmrc to set Node and install deps with npm ci
runs:
  using: composite
  steps:
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci


