name: CI

on:
  workflow_dispatch:
    inputs:
      run-e2e:
        description: "Run Playwright E2E tests"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]
  push:
    branches:
      - master

jobs:
  setup-and-test:
    name: Lint, Unit Tests, Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node and install
        uses: ./.github/actions/node-setup

      - name: Lint
        run: npm run lint

      - name: Run unit tests (Vitest)
        run: npm test -- --run

      - name: Build (production)
        run: npm run build

      - name: Upload production build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 7

  e2e:
    name: Playwright E2E
    needs: setup-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.run-e2e == 'true'
    permissions:
      contents: read
    env:
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      BASE_URL: http://localhost:4321
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node and install
        uses: ./.github/actions/node-setup

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7


