name: Test Cloudflare Secrets

on:
  workflow_dispatch: {}

jobs:
  test-secrets:
    name: Test if secrets are configured
    runs-on: ubuntu-latest
    steps:
      - name: Check CLOUDFLARE_API_TOKEN
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN is NOT set"
            echo "Go to: Settings > Secrets and variables > Actions"
            echo "Add secret: CLOUDFLARE_API_TOKEN"
          else
            echo "✅ CLOUDFLARE_API_TOKEN is set"
            echo "Length: ${#CLOUDFLARE_API_TOKEN} characters"
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Check CLOUDFLARE_ACCOUNT_ID
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID is NOT set"
            echo "Go to: Settings > Secrets and variables > Actions"
            echo "Add secret: CLOUDFLARE_ACCOUNT_ID"
          else
            echo "✅ CLOUDFLARE_ACCOUNT_ID is set"
            echo "Length: ${#CLOUDFLARE_ACCOUNT_ID} characters"
          fi
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Check CLOUDFLARE_PROJECT_NAME
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_PROJECT_NAME }}" ]; then
            echo "❌ CLOUDFLARE_PROJECT_NAME is NOT set"
            echo "Go to: Settings > Secrets and variables > Actions"
            echo "Add secret: CLOUDFLARE_PROJECT_NAME"
            echo "Example value: 10xdevs-flashcards"
          else
            echo "✅ CLOUDFLARE_PROJECT_NAME is set"
            echo "Value: $CLOUDFLARE_PROJECT_NAME"
          fi
        env:
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}

      - name: Summary
        run: |
          echo "================================"
          echo "CLOUDFLARE SECRETS CHECK SUMMARY"
          echo "================================"
          echo ""
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ] || [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ] || [ -z "${{ secrets.CLOUDFLARE_PROJECT_NAME }}" ]; then
            echo "❌ SOME SECRETS ARE MISSING!"
            echo ""
            echo "You need to configure all 3 secrets:"
            echo "1. CLOUDFLARE_API_TOKEN"
            echo "2. CLOUDFLARE_ACCOUNT_ID"
            echo "3. CLOUDFLARE_PROJECT_NAME"
            echo ""
            echo "See: CLOUDFLARE_DEPLOYMENT_SETUP.md for instructions"
            exit 1
          else
            echo "✅ ALL SECRETS ARE CONFIGURED!"
            echo ""
            echo "If deployment still fails, check:"
            echo "1. Token has correct permissions (Account.Cloudflare Pages: Edit)"
            echo "2. Account ID is correct (32-character hash)"
            echo "3. Project name format (lowercase, numbers, hyphens only)"
            echo ""
            echo "See: CLOUDFLARE_DEPLOYMENT_TROUBLESHOOTING.md"
          fi

